import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,readdirSync} from 'node:fs';
import {createHash} from 'node:crypto';
import catalog from '../src/content/catalog.json';
import manifest from '../src/content/publication-manifest.json';
import {verifyPublication} from '../src/lib/publication';
test('EP004 has seven owner-approved pages dated 2026-10-03; original four-episode allowlist remains 27',()=>{const assets=verifyPublication(catalog.episodes as any,manifest);assert.equal(assets.filter(a=>/^EP/.test(a.episode)).length,27);const e=catalog.episodes.find(e=>e.id==='EP004')!;assert.equal(e.productionStatus,'production_complete');assert.ok(['ready','published'].includes(e.publicationStatus));assert.deepEqual(e.approval,{by:'site-owner',date:'2026-10-03'});assert.equal(e.publishRequested,true);assert.deepEqual(e.pages.map(p=>p.id),['P01','P02','P03','P04','P05','P06','P07']);assert.deepEqual(readdirSync('release-assets/EP004').sort(),e.pages.map(p=>p.id+'.webp'));for(const a of assets.filter(a=>a.episode==='EP004')){assert.deepEqual(a.approval,e.approval);assert.equal(createHash('sha256').update(readFileSync('release-assets/'+a.file)).digest('hex'),a.sha256);}assert.equal(catalog.episodes.some(e=>e.id==='EP005'),false);});
test('EP004 cannot use missing, mismatched or held approval',()=>{for(const change of ['held','missing','page-date','asset-date']){const c:any=structuredClone(catalog);const m:any=structuredClone(manifest);const e=c.episodes.find((e:any)=>e.id==='EP004');if(change==='held')e.publicationStatus='held';if(change==='missing')delete e.approval;if(change==='page-date')e.pages[0].approval.date='2026-09-29';if(change==='asset-date')m.assets.find((a:any)=>a.episode==='EP004').approval.date='2026-09-29';assert.throws(()=>verifyPublication(c.episodes,m));}});
